# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.27.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "1.100.0"
    }
  }
}
