subscriptions: any(map(include('subscription'), key=str()), null())
---
subscription:
  listing_id: str(min=36, max=36, matches='^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$', ignore_case=True) # uuid
